credentials:
  name: "Poli Sunil"
  email: "psunil55433@gmail.com"
  phone: "918-239-0503"
  # current_location: "Hyderabad"
  linkedin_url: "https://www.linkedin.com/in/p-sunil-9a9924239"
  comments: "I am excited to apply for this position!"
current_location: "Hyderabad"
resume_path: "Resumes/Sunil Resume.pdf"


# required_questions:
#   "Are you open to a hybrid schedule, based in the SF Bay Area?": "Yes"
#   "Are you authorized to work in the United States?": "Yes"