credentials:
  name: "John Doe"
  email: "jhondow3@gmail.com"
  phone: "464454443"
  # current_location: "Hyderabad"
  linkedin_url: "https://www.linkedin.com/in/p-sunil-9a9924239"
  comments: "I am excited to apply for this position!"
current_location: "Hyderabad"
resume_path: "resumes/resumee.pdf"
resume_file: "resumes/resume.pdf"
first_name: "John"
last_name: "Doe"
pronouns : "he/him"
gender : "Male"
address: "123 Main St"
city: "New York"
state: "New York"
zip: "10001"
country: "United States"
referred : "No"
compensation : "$100,000 - $120,000"
work_status : "H1 Visa"
work_authorization : "I am authorized to work in the country in which this job will be performed"